CLI -- hometask 1
vasyoid/se2019 pull request #1
Opened 2019-01-21 12:47 UTC by vasyoid

2019-02-17 23:10 UTC, ArtyomLobanov requested changes
Паттерн Singleton надо применять с большой осторожностью. У вас явный перебор. Если откинуть условности, у вас весь интерпретатор состоит из глобального состояния в VariablesStorage и набора статических методов, по какой-то прихоти судьбы разложенных в разные файлы. ООП проглядывается только в реализации команд.  Давайте для начала отделим парсер от интерпретатора, состояние интерпретатора перестанем хранить в Singleton-е (А если кому-нибудь понадобится поддерживать два работающих интерпретатора? Или поддержка функций появится и контексты начнут вкладываться?) и позволим пользователям нашего проекта подменять реализации отдельных частей.

2019-02-17 23:10 UTC, ArtyomLobanov commented on cli/build.gradle
> +
Собирающийся jar-файл нельзя запустить т.к. не указана точка фхода в программу

2019-02-17 23:10 UTC, ArtyomLobanov commented on cli/src/main/kotlin/net/netau/vasyoid/command/Wc.kt
> +        }
Давайте либо в if-е return сделаем, либо остальную часть до return в else обернём. А то создаётся ощущение, что даже если if отработал, дальше будет ещё какая-то полезная деятельность. Это немного сбивает с толку.

2019-02-17 23:10 UTC, ArtyomLobanov commented on cli/src/main/kotlin/net/netau/vasyoid/command/Wc.kt
> +        return char.toChar().toString().toByteArray().size
Вы глядит максимально неэффективно. 
Для определения размера файла лучше использовать готовые методы. Тот же [File.length()](https://docs.oracle.com/javase/8/docs/api/java/io/File.html#length--), например. 
Если же используется выход предыдущей команды, то можно уж собрать строку полностью и потом узнать её размер.

2019-02-17 23:10 UTC, ArtyomLobanov commented on cli/src/main/kotlin/net/netau/vasyoid/parser/WordsSplitter.kt
> +            .split('\u0000')
Красиво, конечно, но пока ломает случаи вроде `cat "a".txt`  `"ex"it`, `echo "$prefix"'body'`

2019-02-17 23:10 UTC, ArtyomLobanov commented on cli/src/main/kotlin/net/netau/vasyoid/parser/WordsSplitter.kt
> +            .split('\u0000')
А также не отслеживает проблемы с кавычками
```
> echo text'text
text'text
> echo 'text
tex
```

2019-02-17 23:10 UTC, ArtyomLobanov commented on cli/src/main/kotlin/net/netau/vasyoid/command/Command.kt
> +abstract class Command(val stdin: BufferedReader, val arguments: List<String>, val stdout: BufferedWriter) {
А почему stdin и stdout, а не просто in/input и out/output? Чем они std? Есть другие?

2019-02-17 23:10 UTC, ArtyomLobanov commented on cli/src/main/kotlin/net/netau/vasyoid/command/Cat.kt
> +            System.err.println(e.message)
Откуда-то изнутри писать в System.err не вежливо. Вдруг кто-то будет использовать ваш проект как библиотеку, а он внезапно будет потоки вывода засорять. Бросайте исключения. Их не просто так придумали.

2019-02-17 23:10 UTC, ArtyomLobanov commented on cli/src/main/kotlin/net/netau/vasyoid/command/Wc.kt
> +            val stat = wc(FileInputStream(File(it)).reader(Charset.defaultCharset()).buffered())
А если файла не существует, интерпретатор весело падает.

2019-02-23 21:58 UTC, vasyoid commented on cli/src/main/kotlin/net/netau/vasyoid/parser/WordsSplitter.kt
> +            .split('\u0000')
По поводу замечания про `"ex"it` и подобное. Это было сделано намеренно, так как, на мой взгляд, логично, что кавычки разделяют слова, как и пробелы. А в задании не было требования максимально повторять поведение Bash.

2019-02-23 22:01 UTC, vasyoid commented on cli/src/main/kotlin/net/netau/vasyoid/command/Cat.kt
> +            System.err.println(e.message)
Поменял на исключения везде, кроме внешних команд, потому что они могут выводить что-то в stderr, но всё равно продолжать работать, направлять это на вход следующей команде кажется не очень правильным, а пользователю как-то это показать надо.

2019-03-04 17:26 UTC, ArtyomLobanov commented on cli/src/main/kotlin/net/netau/vasyoid/parser/WordsSplitter.kt
> +            .split('\u0000')
Нууууууууууу, ладно, хотя это, конечно, несколько упрощает задачу.

2019-03-04 18:04 UTC, ArtyomLobanov commented
А что дала замена object на класс содержащий только companion object? Вот эта проблема
>А если кому-нибудь понадобится поддерживать два работающих интерпретатора

всё ещё не решена т.к. CLI - синглтон. Передать ему свою реализацию парсера или интерпретатора всё ещё нельзя.

И исправьте конфликт с матером, пожалуйста.

2019-03-10 21:33 UTC, vasyoid commented
Исправил

2019-03-11 18:36 UTC, ArtyomLobanov commented
@yurii-litvinov

2019-03-18 12:11 UTC, yurii-litvinov approved these changes

2019-03-18 12:11 UTC, yurii-litvinov commented on cli/src/main/kotlin/net/netau/vasyoid/exception/CommandException.kt
> +class CommandException(message: String) : RuntimeException(message)
По-хорошему, исключениям ттоде нужны комментарии --- в каких ситуациях бросается, например

2019-03-23 18:03 UTC, merged