GREP -- hometask 2
vasyoid/se2019 pull request #2
Opened 2019-02-13 00:35 UTC by vasyoid

2019-03-13 12:41 UTC, ArtyomLobanov requested changes
1. grep должен уметь работать с файлами 
```cmd
> grep compile build.gradle
Specify exactly one pattern

Option           Description              
------           -----------              
-A <Integer: n>  print n lines after match
-i               ignore case              
-w               look for full words     
```
2. Проверяйте корректность переданных параметров
```cmd
> cat build.gradle | grep -A -1000 compile
> 
```

2019-03-13 12:41 UTC, ArtyomLobanov commented on cli/src/main/kotlin/net/netau/vasyoid/command/Grep.kt
> +            parser.printHelpOn(System.out)
Не надо писать в стандартные потоки вывода из глубин проекта. Мало ли как потом будет организовано общение с пользователем. Если что-то идёт не так - бросайте исключения.

2019-03-13 12:43 UTC, ArtyomLobanov commented
И, если не сложно, заберите исправления из ветки про cli

2019-03-21 10:06 UTC, ArtyomLobanov commented
Ок. @yurii-litvinov

2019-03-24 17:43 UTC, yurii-litvinov approved these changes
Всё ок, зачтена

2019-03-24 18:15 UTC, merged